# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='proto',
  serialized_pb='\n\ntest.proto\x12\x05proto\"\x13\n\x04\x45\x63ho\x12\x0b\n\x03msg\x18\x01 \x02(\t')




_ECHO = _descriptor.Descriptor(
  name='Echo',
  full_name='proto.Echo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='proto.Echo.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=40,
)

DESCRIPTOR.message_types_by_name['Echo'] = _ECHO

class Echo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHO

  # @@protoc_insertion_point(class_scope:proto.Echo)


# @@protoc_insertion_point(module_scope)
